name = "smolvanillabean"
compatibility_date = "2026-08-27"
pages_build_output_dir = "./public"

[observability]
enabled = false
head_sampling_rate = 1
redact_query_string = false

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1